name: build mega-sdk-python

on:
  push:
    branches:
      - 'master'

    paths-ignore:
    - 'Dockerfile'
    - '.github/workflows/docker-publish.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: breakdowns/mega-sdk-python:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_TOKEN}}
